name: Update Requirements

on:
  push:
    branches:
      - main
      - development

jobs:
  update_requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update requirements.txt
        run: |
          pip freeze > requirements.txt

      - name: Commit changes
        run: |
          git config --global user.name 'mr-cromar'
          git config --global user.email 'blake.cromar@icloud.com'
          git add requirements.txt
          git commit -m "Update requirements.txt" || true
          git push
